export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";

export const INCREMENT_ITEM_QUANTITY = "INCREMENT_ITEM_QUANTITY";
export const DECREMENT_ITEM_QUANTITY = "DECREMENT_ITEM_QUANTITY";

export const SORT = "SORT";
export const PRICE_HIGH_TO_LOW = "PRICE_HIGH_TO_LOW";
export const PRICE_LOW_TO_HIGH = "PRICE_LOW_TO_HIGH";
export const TOGGLE_IN_STOCK = "TOGGLE_IN_STOCK";
export const TOGGLE_FAST_DELIVERY = "TOGGLE_FAST_DELIVERY";
export const SET_PRICE_RANGE = "SET_PRICE_RANGE";

export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
export const VALID_CREDENTIALS = "VALID_CREDENTIALS";
